# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Songs' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Songs

  pod 'AFNetworking', '3.1.0'
  pod 'InflectorKit'
  pod 'TransformerKit'

end


target 'AFIncrementalStoreTests' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Songs

  pod 'AFNetworking', '3.1.0'
  pod 'InflectorKit'
  pod 'TransformerKit'

end
