# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

abstract_target 'AFIncrementalStore' do
    use_frameworks!

    pod 'AFNetworking', '3.1.0'
    pod 'InflectorKit'
    pod 'TransformerKit'

    target 'Songs'
    target 'AFIncrementalStoreTests'
end
